server.port: 7005
server.error.include-message: always

spring.application.name: app

spring.threads.virtual.enabled: true

# --- Spring Cloud Stream & Kafka Configuration ---
spring.cloud:
  function:
    # Use a semicolon to define multiple functions
    definition: consumeCreditAssessed;consumeNotificationSent
  stream:
    bindings:
      # Binding for Credit Service Result
      consumeCreditAssessed-in-0:
        destination: credit.credit_assessed
        group: application-service-group
        content-type: application/json

      # Binding for Notification Service Feedback
      consumeNotificationSent-in-0:
        destination: notification.notification_sent
        group: application-service-group
        content-type: application/json

    kafka:
      binder:
        brokers: localhost:9092
        auto-create-topics: true
# --- Spring Cloud Stream & Kafka Configuration ---

# --- ADDED DB CONFIGURATION START ---
spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.format_sql: true

spring.datasource:
  url: jdbc:postgresql://app-db:5432/app-db
  username: ${POSTGRES_USR}
  password: ${POSTGRES_PWD}
  driver-class-name: org.postgresql.Driver

spring.datasource.hikari:
  initializationFailTimeout: 60000
  maximum-pool-size: 10

# --- ADDED DB CONFIGURATION END ---

# Health checks now only focus on the DB and Disk, not RabbitMQ
management:
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: false # Explicitly disable RabbitMQ health checks

logging:
  level:
    root: INFO
    com.loan.origination.system: INFO
    org.hibernate.SQL: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 80
spring.datasource.url: jdbc:postgresql://app-db/app-db

---
spring.config.activate.on-profile: prod

server.port: 80
spring.datasource.url: jdbc:postgresql://host.minikube.internal:5433/app-db
logging.level.org.hibernate.SQL: WARN