spring.application.name: assessment-mcp-server

spring:
  ai:
    mcp:
      server:
        name: "assessment-mcp-server"
        transport:
          webmvc:
            enabled: true
  main:
    banner-mode: "off"

server:
  port: 7008

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 80