server.port: 7008
server.error.include-message: always

spring.application.name: chat-service
spring.threads.virtual.enabled: true

spring:
  ai:
    model:
      chat: google-genai
      embedding:
        text: google-genai
    google:
      genai:
        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
        embedding:
          enable: true
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768
        chat:
          options:
            model: gemini-2.5-flash
    vectorstore:
      pgvector:
        table-name: chat_home_embeddings
        dimensions: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW
    chat:
      memory:
        cassandra:
          keyspace: chat_memory
          messages-column: chat_messages
          table: chat_memory_store

  cassandra:
    contact-points: easy-apply-assessment-cassandra
    port: 9042
    local-datacenter: dc1
    schema-action: create_if_not_exists
    request:
      timeout: 10s

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest

  datasource:
    url: jdbc:postgresql://chat-pg:5432/chat-db
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initializationFailTimeout: 60000
      maximum-pool-size: 10

home-service:
  base-url: http://easy-apply-home-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring.config.activate.on-profile: docker

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
