{{- define "common.job" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if .Values.command }}
          command: {{ .Values.command | toJson }}
          {{- end }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.configmap.enabled }}
            - name: config-volume
              mountPath: {{ .Values.configmap.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.configmap.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "common.fullname" . }}
        {{- end }}
  {{- end -}}