networks:
  default:
    name: easy-apply

services:
  app-ui:
    build: app-ui
    image: loan-origination-system/app-ui
    mem_limit: 512m
    container_name: easy-apply-app-ui
    hostname: app-ui
    restart: always
    depends_on:
      auth-server:
        condition: service_healthy

  demo-pg:
    image: pgvector/pgvector:pg16
    container_name: easy-apply-demo-pg
    command: [ "postgres", "-c", "wal_level=logical" ] # Required for CDC
    mem_limit: 512m
    environment:
      - POSTGRES_DB=demo-db
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    volumes:
      - ./database/init-demo:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USR} -d demo-db" ]

  home-service:
    build: microservices/home-service
    image: loan-origination-system/home-service
    mem_limit: 512m
    container_name: easy-apply-home-service
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - SPRING_CONFIG_LOCATION=file:/config-repo/application.yml,file:/config-repo/home.yml
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USR}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_AI_GOOGLE_GENAI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - $PWD/config-repo:/config-repo
    depends_on:
      demo-pg:
        condition: service_healthy
      auth-server:
        condition: service_healthy

  app-service:
    build: microservices/app-service
    image: loan-origination-system/app-service
    mem_limit: 512m
    container_name: easy-apply-app-service
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - SPRING_CONFIG_LOCATION=file:/config-repo/application.yml,file:/config-repo/app.yml
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USR}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
    volumes:
      - $PWD/config-repo:/config-repo
    depends_on:
      demo-pg:
        condition: service_healthy
      auth-server:
        condition: service_healthy

  gateway:
    build: spring-cloud/gateway
    image: loan-origination-system/gateway
    mem_limit: 512m
    container_name: easy-apply-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_LOCATION=file:/config-repo/application.yml,file:/config-repo/gateway.yml
      - SERVER_SSL_KEY_STORE_PASSWORD=${GATEWAY_TLS_PWD}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USR}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PWD}
    volumes:
      - $PWD/config-repo:/config-repo
    ports:
      - "8443:8443"
    depends_on:
      auth-server:
        condition: service_healthy

  auth-server:
    build: spring-cloud/authorization-server
    image: loan-origination-system/auth-server
    mem_limit: 512m
    container_name: easy-apply-auth-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_LOCATION=file:/config-repo/application.yml,file:/config-repo/auth-server.yml
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USR}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PWD}
    volumes:
      - $PWD/config-repo:/config-repo
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:4004/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60
