include("api")
include("util")
include("microservices:product-service")
include("microservices:review-service")
include("microservices:rating-service")
include("microservices:product-composite-service")
include("spring-cloud:authorization-server")