fullnameOverride: home-service

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "4004"
  prometheus.io/scheme: http
  prometheus.io/path: "/actuator/prometheus"

image:
  name: home-service

# Environment variables from docker-compose
env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: "file:/config-repo/application.yml,file:/config-repo/home.yml"

# Using your product-style pattern for mounting config files
configmap:
  enabled: true
  volumeMounts:
    mountPath: /config-repo

# Standard Spring Boot Probes
livenessProbe_enabled: true
readinessProbe_enabled: true