fullnameOverride: credit-db

annotations:
  sidecar.istio.io/inject: "false"

image:
  repository: pgvector
  name: pgvector
  tag: pg16
  pullPolicy: IfNotPresent

# Required for Debezium CDC
command: [ "postgres", "-c", "wal_level=logical" ]

env:
  POSTGRES_DB: credit-db
  POSTGRES_USER: ${POSTGRES_USR}
  POSTGRES_PASSWORD: ${POSTGRES_PWD}

persistence:
  enabled: true
  mountPath: /docker-entrypoint-initdb.d
  # This corresponds to ./database/credit-init

ports:
  - containerPort: 5432

service:
  ports:
    - name: credit-db
      port: 5432

resources:
  limits:
    memory: 512Mi