apiVersion: v2
appVersion: "2.5"
description: A Helm chart for Debezium (Kafka Connect)
name: connect
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common