secrets:
  # DB Server Admin Credentials (shared across all 4 DBs for simplicity in dev)
  postgres-server-credentials:
    POSTGRES_USR: home-user-prod
    POSTGRES_PWD: home-pwd-prod

  # Application DB Connection Credentials
  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: home-user-prod
    SPRING_DATASOURCE_PASSWORD: home-pwd-prod

  # AI Integration
  ai-credentials:
    GEMINI_API_KEY: "AIzaSyA53KrtM7iN0L0-SIVyFPoaU_9zZHAjK58"

# Infrastructure Configuration
postgres:
  envFromSecretRefs:
    - postgres-server-credentials

app-db:
  envFromSecretRefs:
    - postgres-server-credentials

credit-db:
  envFromSecretRefs:
    - postgres-server-credentials

notify-db:
  envFromSecretRefs:
    - postgres-server-credentials

# Microservices Configuration
home-service:
  envFromSecretRefs:
    - postgres-credentials
    - ai-credentials

app-service:
  envFromSecretRefs:
    - postgres-credentials

credit-service:
  envFromSecretRefs:
    - postgres-credentials

notification-service:
  envFromSecretRefs:
    - postgres-credentials

# Frontend
app-ui:
  service:
    type: LoadBalancer # Expose UI for dev access