apiVersion: v2
appVersion: "1.0"
description: Production Environment for Loan Origination System
name: prod-env
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common

  # Spring Cloud Core
  - name: auth-server
    version: 1.0.0
    repository: file://../../components/auth-server

  # Microservices
  - name: home-service
    version: 1.0.0
    repository: file://../../components/home-service
  - name: app-service
    version: 1.0.0
    repository: file://../../components/app-service
  - name: assessment-service
    version: 1.0.0
    repository: file://../../components/assessment-service
  - name: notification-service
    version: 1.0.0
    repository: file://../../components/notification-service

  # Frontend
  - name: app-ui
    version: 1.0.0
    repository: file://../../components/app-ui