secrets:
  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: home-user-prod
    SPRING_DATASOURCE_PASSWORD: home-pwd-prod
  ai-credentials:
    GEMINI_API_KEY: "AIzaSyA53KrtM7iN0L0-SIVyFPoaU_9zZHAjK58"

# 1. Define the reusable template (anchor)
.microservice_defaults: &microservice_defaults
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "prod"
  envFromSecretRefs:
    - postgres-credentials
  resources:
    requests:
      memory: 300Mi
    limits:
      memory: 600Mi

# 2. Apply the template to your services
app-service:
  <<: *microservice_defaults

credit-service:
  <<: *microservice_defaults

notification-service:
  <<: *microservice_defaults

# 3. Special case for home-service (merges defaults + adds ai-credentials)
home-service:
  <<: *microservice_defaults
  envFromSecretRefs:
    - postgres-credentials
    - ai-credentials

# Infrastructure
postgres:
  resources:
    limits: { memory: 1Gi }

kafka:
  resources:
    limits: { memory: 2Gi }

# Istio Service Mesh Configuration
virtualServices:
  - app-ui
  - home-service
  - app-service

destinationRules:
  - name: auth-server
  - name: home-service
    subsets:
      - labels: { version: v1 }
        name: current
  - name: app-service
    subsets:
      - labels: { version: v1 }
        name: current

app-ui:
  image:
    tag: v1
  service:
    type: ClusterIP